### ISSUE TITLE
Not copying all images in uploads folder

### ISSUE THREAD

**Issue by markgenest** [patrickposner/simply-static#12]
Hi Patrick,

First off, let me say this is a GREAT plugin for WordPress. Saves me a tremendous amount of time!

I generate a static site into a repository that I then push to Netlify. When I generate the static site, all the images in the uploads folders are not copied over. I have to manually copy the `wp-content/uploads/year/date` folders over the static folder to fill in the missing images. 

Just wondering if this is a bug or if there are file limits to the free version.

Thanks so much!

**Comment by omartan** [comment]
Agreed, I have not only images but some JS files not being transferred over as well

**Comment by netagence** [comment]
Based on my understanding of how static site generation works,, it would make sense that only medias linked to pages/posts would be copied over ? Is it possible that the images and JS files you found not copied over would be "orphan files" ? Where are the JS located ? Did you find pages in the static sites with broken links / missing images ?

**Comment by markgenest** [comment]
Yes that is normally how the SSG works I would think. There seems to be several issues:

1. It won't copy all active images from `/wp-content/uploads/year/month/....`  folders. Orphans aren't a problem as it doesn't matter whether they are copied or not. I have to manually copy the entire folder and overwrite to add the missing images so they will load correctly
2. Since the latest update, it doesn't seem to want to copy over any new pages created. Instead of adding a new page folder with index.html, it ignores new pages, even though they are published. I have to manually add the page paths into the includes list. This is why I was wondering if there are size limitations or number of pages/images on the free version
3. It ignores folders created in the `/wp-content/themes/theme-name/....` These have to be manually added in as well

**Comment by patrickposner** [comment]
I'm closing this issue now as it is to general.
There are several factors coming into play here.

I already improved the $match_tags list to include things like <picture> tags and inline CSS added to divs and various other HTML tags, but there will always be something the crawler can not pick up automatically.

To ensure that everything is getting picked up, you may want to follow the W3C, validate your website [here](https://validator.w3.org/), fix all outstanding problems and you will get a 99% chance that Simply Static will export everything displayed on the website.
