### ISSUE TITLE
Add support for decentralized storage deployment on Skynet

### ISSUE THREAD

**Issue by dghelm** [patrickposner/simply-static#18]
I work on a decentralized storage project called [Skynet](https://siasky.net/), which (among other things) makes deploying static websites very straightforward. We often have community members asking how to deploy WordPress sites to Skynet, and don't have a great solution.

Would you be open to a PR that added this feature?

**Comment by patrickposner** [comment]
@dghelm Sure! I love the approach of your project and would be happy to merge a PR integrating it!
