### ISSUE TITLE
404 page isn't generated 

### ISSUE THREAD

**Issue by YumiSuki** [patrickposner/simply-static#21]
Hello everyone,

Today I found that 404 wasn't generated by simply static. I have manually add the page URL using  _Additional URLs_ but it still doesn't get generated. So, please kindly check this bug. Thanks.

**Comment by patrickposner** [comment]
@YumiSuki The usual 404 page from WordPress will not work because it gets generated dynamically.
You have to create a page for 404 and configure it (depending on your hosting).
