### ISSUE TITLE
meta element content attribute changes

### ISSUE THREAD

**Issue by j-brand** [patrickposner/simply-static#22]
Hi,
since the update the static site generation changes the elements in the head. e.g. meta viewport
It looks like that the last part of the URL ist prepended to the content attribute of meta elements.

Version: 2.1.5.3

before generation:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

after generation:
`<meta name="viewport" content="/exhibition/width=device-width, initial-scale=1">`

**Comment by tremlas** [comment]
Also applies to <meta http-equiv> which appends the content to the URL and tries to fetch it even if the http-equiv isn't a link (such as Content-Type). I'd suggest that <meta http-equiv> tags should just be skipped (even if you could argue that default-style is a link)

**Comment by patrickposner** [comment]
@tremlas You are absolutely right. I reverted that now and release a new update, thanks!
For cases like Twitter Cards and other URL-like content in meta, we will be using the introduced filter ss_match_tags now.
