### ISSUE TITLE
version number style

### ISSUE THREAD

**Issue by wp-seth** [patrickposner/simply-static#24]
which version number style does this package use at the moment? unfortunately it's not semver any longer, because the changes from 2.1.0 to 2.1.5.5 don't seem to be backward compatible.

**Comment by patrickposner** [comment]
Hey @wp-seth,

it's still semver.

The dependencies of Simply Static got an update (which increased the requirements of PHP and changed a couple of things), but there weren't any breaking changes in Simply Static itself.

**Comment by wp-seth** [comment]
> increased the requirements of PHP

... which i'd consider a breaking change for all users with an older php version. and it's for sure not just a patch.

furthermore is #23 a big indicator that the changes _are_ breaking.
