### ISSUE TITLE
simply static invalid path

### ISSUE THREAD

**Issue by NourEssalam** [patrickposner/simply-static#25]
I want to export my WP website to GitHub pages but simply static not working I tried many things, suddenly I took a look at diagnostic page in the simply static plugin,
it says that my directory paths are invalid, I can’t find where is the problem ..
please save me – thanks!

+ Checking if Additional File/Dir C:\wamp64\www\momten-blog\wp-content\uploads is valid –> Not a valid path

+ Checking if WordPress can make requests to itself from –> Received a 301 response. This might indicate a problem
Checking if Additional File/Dir C:\wamp64\www\momten-blog\wp-content is valid –> Not a valid path

**Comment by NourEssalam** [comment]
I want to export my WP website to GitHub pages but simply static not working I tried many things, suddenly I took a look at diagnostic page in the simply static plugin,
it says that my directory paths are invalid, I can’t find where is the problem ..
please save me – thanks!

+ Checking if Additional File/Dir C:\wamp64\www\momten-blog\wp-content\uploads is valid –> Not a valid path

+ Checking if WordPress can make requests to itself from –> Received a 301 response. This might indicate a problem
Checking if Additional File/Dir C:\wamp64\www\momten-blog\wp-content is valid –> Not a valid path

**Comment by patrickposner** [comment]
Hey @NourEssalam,

that may be because you are using WAMP.
I already wrote about local environments here: https://patrickposner.dev/docs/simply-static/problems-with-local-development
