### ISSUE TITLE
No sitemap file in generated static site

### ISSUE THREAD

**Issue by ampliads** [patrickposner/simply-static#26]
Dear @patrickposner 
Your plugin is amazing!
We are successfully able to set it with local dev on laragon (with rankmath !) and it functions like a charm! (we used composer install)
The only problem is, there is no sitemap.xml in the output dir. 
Let me know how to enable sitemaps.xml in output static site.

With thanks in advance!

**Comment by ampliads** [comment]
The way I found is to manually add the sitemap url (in our case, its https://imdrviral.com/sitemap_index.xml, but it may change as per seo / sitemap generator plugin used) at Simply-static > settings > INCLUDE/EXCLUDE > Additional URLs
![2022-02-22_13-30-01](https://user-images.githubusercontent.com/71036669/155088387-9c839636-889b-4aaa-bdc9-d4205f1061ae.png)

Surprisingly, this single url addition has fetched all subsequent sitemaps (page, category, post etc) but it also created wp-login.php as well! (may be, bug?)

**Comment by patrickposner** [comment]
Hey @ampliads,

thanks for your report!

That is indeed the way to go.
All that needs to be added is the main XML Sitemap file, as SImply Static can parse and extract URLs from here.

As the Sitemap isn't linked from the frontend anywhere, it has to be added within "Additional URLs" to get picked up by the crawler.

wp-login.php:

This is already fixed!
