### ISSUE TITLE
Ensure previous static files are cleared from Local Directory before copying new files

### ISSUE THREAD

**Issue by adamsilverstein** [patrickposner/simply-static#30]
Note: thanks for the great plugin! I discovered this issue while using your plugin and it feels like a bug, I have a PR prepared to fix it for your consideration.

## Description
When using the `Local Directory` output option, old files are not currently removed when you perform the Generate action. Because of this files that were removed are still accessible on the static site.

## Steps to reproduce
1. Set generation to use a Local Directory.
2. Create a new post "test-post" and generate the static site
3. Delete the "test-post"
4. Generate the site again

Expected result: the URL is no longer available in the static site
Actual result: the URL is still available (because it was never removed)

Recommended solution: clear the local directory folder before copying the file. Potentially this could be a UI option, however I would suggest it default to on.

**Comment by patrickposner** [comment]
Merged now, Issue closed! Thanks!

**Comment by weibeld** [comment]
Is this supposed to work in version 2.1.7.1? Currently, this doesn't seem to work. When deleting a page or post, the old files are still there in the local directory when regenerating the files.

**Comment by adamsilverstein** [comment]
@weibeld it should be fixed; I can give it a test to verify. Any special steps to reproduce? are you testing this locally or how are you sure the files remain?

**Comment by patrickposner** [comment]
Hey @weibeld,

sorry I missed the comment here.

The story is a bit longer, but I try to keep it short:

It was implemented in an older version, but I reverted the pull request.
We haven't thought about people that do not want to delete files from the local path on each static export.

Now with version 2.1.8 released, there is an option to activate that (Simply Static -> Settings -> Advanced -> Additional Settings -> Clear directory before static export).

Thanks @adamsilverstein thanks for your help!

**Comment by adamsilverstein** [comment]
thanks for pointing out the option @patrickposner - that makes perfect sense that users would want to control this behavior.

**Comment by weibeld** [comment]
@patrickposner Thanks for the info and the feature.

When I just tested it with v2.1.8, enabling the "Clear local directory before export" indeed causes the directory to be cleared, however, no new files are created in it too. That is, after running an export, the export directory is completely empty.

Do you know anything about this issue?
