### ISSUE TITLE
Backslash Instaed of Forward Slash in Fetch URL Created from Additional Dir on Windows using Bitnami Wordpress Stack

### ISSUE THREAD

**Issue by neilmahaseth** [patrickposner/simply-static#37]
While creating URLs from additional dir simply static passes the native windows directory separator (Backslash) instead of converting it to  Forward Slash. This causes those URLs to return a 404 error. I am using a local deployment of WordPress by Bitnami. I was able to solve the problem by adding a string replace call in the fetch function. 

class-ss-url-fetcher.php
```
public function fetch( Page $static_page ) {
$static_page->url = str_replace('\\', '/', $static_page->url);
```

**Comment by patrickposner** [comment]
@neilmahaseth Good catch! I implemtend the check for the URL now.
