### ISSUE TITLE
Plugin stops changing website URL in metatags

### ISSUE THREAD

**Issue by matt08** [patrickposner/simply-static#44]
Plugin stops change URLs to `Destination URLs` in metatags i.e.

```
<meta property="og:url" content="https://dev.domain.tld/slug/">
<meta property="og:image" content="https://dev.domain.tld/wp-content/uploads/image.jpg">
<meta property="og:image:secure_url" content="https://dev.domain.tld/wp-content/uploads/image.jpg">
<meta name="twitter:image" content="https://dev.domain.tld/wp-content/uploads/image.jpg">
```

in the latest version `2.1.5.9`. 
In `2.1.5.8` everything is OK.

**Comment by patrickposner** [comment]
Hey @matt08,

thanks for your report!

That has to do with removing the catch all rule in Simply Static and instead working with a fixed set of matching tags.
I add meta tags now to the tag list and once I reviewed all outstanding GitHub issues, I release a new update which should fix that.

**Comment by patrickposner** [comment]
Added a better check now so that only URLs are getting replaced in meta and tested everything successfully.
I'm closing the issue now as I will release the update soon!
