### ISSUE TITLE
Form fields

### ISSUE THREAD

**Issue by djmtype** [patrickposner/simply-static#45]
I understand a server is required to process form fields, but why does Simply Static remove the the input fields, and replace them with `<\/span>`? Is it possible to show the actual input forms as intended?

**Comment by patrickposner** [comment]
Hey @djmtype,

thanks for creating an issue.

Simply Static does not replace or remove any input fields from your form.

Once you export a page that contains a form, Simply Static does not change anything within your form (besides the action URL if your are using the pro version).

Take a look here: https://patrickposner.dev/support/
This is my own static website generated by Simply Static with a form.

![simply-static-form](https://user-images.githubusercontent.com/15874198/189868801-b46c8b7b-1271-4553-9d1f-e33029d78cdf.png)
