### ISSUE TITLE
Various URLs no longer replaced after 2.1.5.8

### ISSUE THREAD

**Issue by juz501** [patrickposner/simply-static#54]
We noticed an anomaly after this version where URLs are no longer replaced:

- Inline script tags
- In custom html attributes
- Within input tag values where URLs are added via `get_the_permalink()`
- In schema json/ld

In general, we are sticking with 2.1.5.8 which has the catch all.  Please add the catch all at least as a fallback option or another way to cater for the new method.

**Comment by patrickposner** [comment]
@juz501 thanks for letting me know!

There will be an option in 2.1.8 to reenable the catch all rule now for static exports in Simply Static -> Settings -> Advanced! 😉

![force-replacement](https://user-images.githubusercontent.com/15874198/201937882-ba3a769a-7a64-4142-86df-7fa1f3c4b40e.png)
