### ISSUE TITLE
CSS-style gets altered

### ISSUE THREAD

**Issue by linuxlurak** [patrickposner/simply-static#55]
Simply Static alters this code somehow:
`<div class="wp-container-6 wp-elements-480198b7852aa212b599ef4e20fb7033 wp-block-group alignfull has-background-color has-text-color has-background has-link-color" style="background-color:/#990404;padding-top:0px;padding-bottom:0px">`
`

background-color:#990404;` results in `background-color:/#990404;`

An additional / gets inserted...

**Comment by linuxlurak** [comment]
Problem not existing in v 2.1.6

**Comment by jweston491** [comment]
I am also experiencing this issue. @linuxlurak thanks for pointing out that downgrading to 2.1.6 fixes. I will try it out

**Comment by patrickposner** [comment]
Merged now with https://github.com/patrickposner/simply-static/issues/10
