### ISSUE TITLE
Google Analytics 4 not working

### ISSUE THREAD

**Issue by lasida** [patrickposner/simply-static#58]
hi. @patrickposner  thanks for creating this plugin 😃 

i used google analytics 4 for tracking, and i place the tracking code using Elementor Code in head tag.
and it is not working, when i figure out the javascript code is commented and not push the tracking to GA4

can you help me for uncommented, or give hint to that commented line code ?
![image](https://user-images.githubusercontent.com/8340974/202838099-7d852729-8926-473c-9ada-c7fdfddb445c.png)

Thanks

**Comment by patrickposner** [comment]
That will be covered here: https://github.com/patrickposner/simply-static/issues/63

For now, you want to activate the new option in Simply Static -> Settings -> Advanced -> Additional Settings -> Force replace URLs to make sure the URL inside your GA4 script tag is updated accordingly (that should fix the issue for now).

**Comment by lasida** [comment]
nice, thanks for the solution 👌 I will try it

**Comment by lasida** [comment]
![image](https://user-images.githubusercontent.com/8340974/209094949-4f12a85c-7892-4855-a013-f40ccbcb59bc.png)

Hi @patrickposner, i was trying new version v2.2 and in this version i found a key generated ini type attribute, when i remove this key, javascript was loaded, and google analytics was works properly

i want ask how to remove this key, and make sure the type printed as type="text/javascript"

I was trying in configuration
Advanced -> Force URL replacements : TRUE
Destination URL : Custom, Relative, Offline

but i can find how to remove that key

Thanks

**Comment by lasida** [comment]
Update :: i have been tested in Cloudflare Pages and its working very well 😃 

I think my hosting server caused this issue😄

**Comment by patrickposner** [comment]
Woop, woop! Thanks for the update @lasida! 😁
