### ISSUE TITLE
Improving image extraction

### ISSUE THREAD

**Issue by patrickposner** [patrickposner/simply-static#61]
We currently extracting images by attributes in a specific tag list.

All matching tags are stored in the $match_tags property here: https://github.com/patrickposner/simply-static/blob/dcd0cf3714388cfd63f9ba47587dc1ea79381ae9/src/class-ss-url-extractor.php#L29

This works fine in most cases and the list gets extended regularly, but we need a better solution for some use cases.

**Extracting images from srcset:**

We using a regex pattern to do that here: https://github.com/patrickposner/simply-static/blob/dcd0cf3714388cfd63f9ba47587dc1ea79381ae9/src/class-ss-url-extractor.php#L381

This does produce mixed results and may break the markup for responsive images in WordPress.

**Removing query strings**

A lot of themes and image optimization plugins work with query strings to dynamically output the optimized version of an image.

We should handle that and make sure to remove those strings before converting the page to HTML.
A good example is the Brizy Builder as mentioned here: https://github.com/patrickposner/simply-static/issues/49

We should also do that within the dedicated function right here: https://github.com/patrickposner/simply-static/blob/dcd0cf3714388cfd63f9ba47587dc1ea79381ae9/src/class-ss-url-extractor.php#L381

**Extracting image URLs encoded with base64**

We currently extracting URLs from CSS as shown here: https://github.com/patrickposner/simply-static/blob/dcd0cf3714388cfd63f9ba47587dc1ea79381ae9/src/class-ss-url-extractor.php#L408

We should also handle base64 encoded image URLs as this seems to be quite common in a lot of themes and pagebuilders these days (Revolution Slider is also a good example here).

**Comment by patrickposner** [comment]
@igorbenic 

I tested that again and got decent results with srcsets.

One issue that still persists are images with specifiers (like '2x' or '3x') are not separated from the specifier itself, resulting in a 404 (i.e. "https://wp.mysite.com/wp-content/uploads/2022/09/myimage@2x.png 2x").

Not sure if this is really a major thing we need to handle within Simply Static, but worth checking.
A good plugin to test this is https://wordpress.org/plugins/wp-retina-2x/

**Comment by igorbenic** [comment]
@patrickposner I'll check that out.

As for the query string part where there is no image in URL, just the query string that returns an image, do you agree with the approach where we get the contents of the query string (image) and save it in the appropriate folder, then replace that whole part with the path to that folder?

**Comment by patrickposner** [comment]
@igorbenic absolutely! In 99.99% of the cases, I think that is exactly what the users expect!

**Comment by patrickposner** [comment]
Another thing that already happens quite often in the last weeks (within support) is that images aren't get copied over to the static website if lazy loaded is activated in WordPress.

We may disable them by default to avoid that with:

`add_filter( 'wp_lazy_loading_enabled', '__return_false' );`

**Comment by patrickposner** [comment]
We are closing that for now as all integrations are done.
If something new pops up, we follow up with a new issue.
