### ISSUE TITLE
Improving URL replacement in script tags

### ISSUE THREAD

**Issue by patrickposner** [patrickposner/simply-static#63]
We are currently checking the src attribute of script tags for URL replacements, but that doesn't work if the URL is added within the script tag itself.

We currently handle that with an additional option (Simply Static -> Settings->Advanced->Additional Settings->Force URL replacement), but it should work without it as well.

Here we search and replace the URLs by checking the entire body: https://github.com/patrickposner/simply-static/blob/dcd0cf3714388cfd63f9ba47587dc1ea79381ae9/src/class-ss-url-extractor.php#L237

Here we are searching and replacing URLs within the src attribute of script tags: https://github.com/patrickposner/simply-static/blob/dcd0cf3714388cfd63f9ba47587dc1ea79381ae9/src/class-ss-url-extractor.php#L422

We should copy the force_replace_urls method and limit the execution to script tags.

The old method will stay in the core for compatibility reasons, but it's good to have a more robust solution just for URLs in script tags.

**Comment by igorbenic** [comment]
@patrickposner I am looking at the `HtmlDomParser` and innerhtmlKeep seems to be a function alias, not a variable where we can put the content. Was this working before? 

Maybe I am completely wrong here, never had such complex work with `HtmlDomParser` 😆

**Comment by patrickposner** [comment]
That's a bit of magic from the ported version (using PHP DomDocument) we're using in Simply Static.

Here is an example with outertext (which is maybe more common): [example_modify_contents](https://github.com/voku/simple_html_dom/blob/master/example/example_modify_contents.php)

There is also an example for modifying attributes: [example_modify_attribute](https://github.com/voku/simple_html_dom/blob/master/example/example_modify_attribute.php)

So you can update (almost) everything from an element this way without changing the element itself (or generating a new one)
