### ISSUE TITLE
Yoast sitemap not included in zip output

### ISSUE THREAD

**Issue by BenJackGill** [patrickposner/simply-static#66]
When I have Yoast SEO plugin installed and I generate a static site, the sitemap is not included in the zipped output.

Some older posts on the WordPress plugin support forum say that this was a bug that has been fixed. But it doesn’t work for me. Maybe the bug is back?

Here is what I am using:

LocalWP 6.5.2 (PHP 8.1.9 / nginx / MySQL 8.0.16)
WordPress 6.1.1
Simply Static 2.1.9
Yoast 19.11

P.S. I also posted this on the WordPress plugin support forum but I thought it would get more visibility.

**Comment by patrickposner** [comment]
@BenJackGill, you need to manually include it in Simply Static ->Settings-> Include/Exclude -> Additional URLs right now.
We are working on doing that automatically right here: https://github.com/patrickposner/simply-static/issues/62

**Comment by BenJackGill** [comment]
When I include it inside Additional URLs it produces an error.

These are my settings,...

**Settings > Include/Exclude > Additional URLs**:

http://www.heapsbetter.local/sitemap_index.xml
http://www.heapsbetter.local/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl

**Settings > Include/Exclude > Additional Files and Directories**:

/Users/MaryJane/Local Sites/heapsbetter/app/public/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl

But it does not work because when I host it online and visit the live sitemap at this http://heapsbetter.com/sitemap_index.xml I get an error saying this:

```
Error loading stylesheet: An unknown error has occurred (805303f4)
http://www.heapsbetter.local/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl
```

Notice that the URL of the error is **http://www.heapsbetter.local**/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl but my live domain is actually **http://heapsbetter.com**.

So I think the problem is Simply Static has has not converted that URL.

Is there anyway I can fix this?

**Comment by BenJackGill** [comment]
@patrickposner Wondering if you saw the update above? Just want to make sure it's considered for future releases :)
