### ISSUE TITLE
Simply Static 2.2: Unable to copy file to destination 

### ISSUE THREAD

**Issue by Forceflow** [patrickposner/simply-static#73]
I've set up simply_static to output to: `/home/jeroen/static`. 

After upgrading to 2.2, it can't copy files anymore after the generation process, and the plugin starts **appending** directories to the output directory's name. Like, I have a "contact" page on my website, that normally goes in `/home/jeroen/static/contact`, but in the 2.2 version, it gets created in `/home/jeroen/staticcontact`

- I've tried enabling/disabling the clear directory option, doesn't make a difference.
- I've verified that the /home/jeroen/static directory is writable, diagnostics flag it as okay.
- I've downgraded back to 2.1.9 to verify that this behaviour was introduced in 2.2, and that is correct. 2.1.9 doesn't have these problems.

**Comment by AndrewKahr** [comment]
Hmmm if that's the case then that means there are different behaviors based on platform. When Wordpress gets hosted on a windows base, it adds slashes to the end of paths automatically so the latest fix dropped the slash since they started doubling up.

**Comment by Forceflow** [comment]
> Hmmm if that's the case then that means there are different behaviors based on platform. When Wordpress gets hosted on a windows base, it adds slashes to the end of paths automatically so the latest fix dropped the slash since they started doubling up.

I see. I'm running on a shared-hosting Linux-based VPS. 

The output folder always gets a slash added in the config field, btw, it's `/home/jeroen/static/`

**Comment by AndrewKahr** [comment]
I'll look into making the slash removal more discretionary or improve the path joining method so it doesn't miss or duplicate the slash.

**Comment by Forceflow** [comment]
> I'll look into making the slash removal more discretionary or improve the path joining method so it doesn't miss or duplicate the slash.

Thank you. This issue does seem kind of serious, so I'd suggest quickly updating or pulling the latest release? People who run simply-static on linux-based systems will see a lot of additional folders created and their sites not updated.

**Comment by AndrewKahr** [comment]
@Forceflow I've put together #74 which should fix it. I tested pathing for both Windows and Linux style paths, however, I don't have a linux box on hand to test a full wordpress run. If you download the changes from [here](https://github.com/Madrona-Games/simply-static/tree/bug/cross-platform-paths-broken) that would be great to help verify it works. We will need to wait for @patrickposner to actually merge the changes and push an update though.

**Comment by patrickposner** [comment]
@Forceflow @AndrewKahr 

For now, I reverted the modifications in the class-ss-transfer-files-locally task.php and pushed a quick update.
This works fine for most cases but has some Windows environment limitations.

The PR looks like a pretty good improvement for path handling in general.
I test it, try to replicate it in different environments (Mac/Windows/Linux), and if all is okay, merge it.

However, we may not want to push another update directly, so these modifications will be included in a (larger) 2.2.2 update.

**Comment by AndrewKahr** [comment]
Sounds good, my apologies for the bug I introduced.

**Comment by patrickposner** [comment]
@AndrewKahr all good. I appreciate all the help on Simply Static! I, for myself, introduced countless bugs and needed to implement bug fixes right away 😅

**Comment by AndrewKahr** [comment]
Happy to help! This plugin is a godsend for static site conversion.

**Comment by Forceflow** [comment]
Yeah +1, thank you for the quick response / solution. I've started using this plugin recently and I love it.
