### ISSUE TITLE
A problem about get_permalink() function.

### ISSUE THREAD

**Issue by roywangdev** [patrickposner/simply-static#79]
When an HTML page is generated, this function is called many times. Only the first time this function is called, the domain name will be replaced. The rest of the calls are unsuccessful.

Suppose the domain name I need to replace is demo.com

My wordpress site domain name is wp.demo.com

When I generate a page, I will call this function to generate a wp.demo.com/xxx page, but only the first time I call it correctly, it is replaced by demo.com/xxx. When calling the second and third time, the generated file is still wp.demo.com/xxx

After searching, this problem is generated in versions after 2.1.5.6.

**Comment by patrickposner** [comment]
Hey @roywangdev,

that does not seem to be a general issue.
It may be specific to the theme/plugin combination.

You can always force the replacement by activating Simply Static -> Settings -> Advanced -> Force Replace URLs.
This brings back the catch-all rule available in versions before 2.1.5.7.
