### ISSUE TITLE
Multisite-Support

### ISSUE THREAD

**Issue by patrickposner** [patrickposner/simply-static#87]
Simply Static only works within a subsite due to the simply_static_pages database table.
We don't even add much information about how to use Simply Static within a multisite environment.

How a multisite integration may work:

- simply_static_pages table decoupled from the subsite and instead added to the network
- adding a column with the Site-ID to differentiate between subsites
- include the settings in the network page and add a select menu to choose the subsite to export (or export stating from the network page if subdirectories are used)
- An option to hide settings on a subsite level

These are just a bunch of ideas out of my head. Feel free to extend that list as needed!

**Comment by igorbenic** [comment]
@patrickposner Added a new column site_id and made sure when finding Pages, we're searching only within such site.

Questions:
- currently, we delete all old static-generated files before creating a new one. If on Site 2, I should only delete static files/ZIP related to that site, right?
- should we list all generated sites for network admins to see?

**Comment by patrickposner** [comment]
@igorbenic 

**Deleting files:**

We clear the database table on each run. We should only clear the records that are from the specific site ID.
We need to make sure that we are not clearing all the files themselves if using "Local Directory" as the delivery method, as this is only be done if you activate "Clear directory before static export" in Simply Static -> Settings -> Advanced.

**List generated sites**

I would only show the latest static export in the network settings and instead add the Site ID as a column in the export log.
Once we have a select menu at the top for selecting the site to export, that should be fine.

**Comment by beckej13820** [comment]
I manage multisites at my college, where often we have sites that are very active for a short period of time, but then want to be archived and stay on the web as an archive of the project. 

If there was a way to archive sites from the multisite that are no longer in development, and freeze them as a static site so that the subsite could be removed, archived, or deactivated, it could be very useful.
