### ISSUE TITLE
simply_static query string being added to some links

### ISSUE THREAD

**Issue by ChristianHoffmann** [patrickposner/simply-static#89]
Unfortunately a recent change to simply static means that a query string similar to ‘?simply_static_page=1078669’ is appearing on some links and this causes an unnecessary page change. It’s particularly noticable on pages with page numbers/link generated by paginate_links or where a redirection managed by the ‘Redirection’ plugin is triggered. I’d like some way to suppress this query string appearing in the generated HTML.

Edit:
I installed a default installation of wordpress on MAMP locally and to double check if that might be the fault also on my webserver. I can confirm that Simply Static adds this query to the links for paginated Links only. The Links are working technically and the sites are also generated but of course it is preferable to remove that.

Thanks in advance,
Christian

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/6329973/212560064-4926310d-bed0-4dda-a351-a0d2f51ad653.png">

**Comment by tremlas** [comment]
Just for tracking and as an fyi: this is the problem I previously reported on the wordpress support forum
